package bg.blacksea.buoys.advertising

import bg.blacksea.buoys.domain.activity.MarineActivityType
import java.time.*

class AdvertisingSession(private val now:()->Instant={Instant.now()}){private val impressions=mutableMapOf<String,Int>();private val last=mutableMapOf<String,Instant>();fun canShow(c:SponsoredCampaign):Boolean{val count=impressions[c.id]?:0;val recent=last[c.id]?.let{Duration.between(it,now()).toMinutes()<c.minimumIntervalMinutes}?:false;return count<c.maxImpressionsPerSession&&!recent};fun record(c:SponsoredCampaign){impressions[c.id]=(impressions[c.id]?:0)+1;last[c.id]=now()}}
fun selectCampaign(campaigns:List<SponsoredCampaign>,configuration:AdvertisingConfiguration,preferences:UserAdvertisingPreferences,placement:AdPlacement,destinationId:String?=null,activity:MarineActivityType?=null,session:AdvertisingSession=AdvertisingSession(),now:Instant=Instant.now()):SponsoredCampaign?{
 if(!configuration.advertisingEnabled||!preferences.allAdsEnabled)return null
 return campaigns.asSequence().filter{it.enabled}.filter{it.startsAt?.isAfter(now)!=true&&it.endsAt?.isBefore(now)!=true}.filter{placement in it.placements}.filter{it.destinationIds.isEmpty()||destinationId in it.destinationIds}.filter{it.activityTypes.isEmpty()||activity in it.activityTypes}.filter{preferences.dismissedCampaigns[it.id]?.let{d->Duration.between(d,now).toHours()<it.dismissDurationHours}!=true}.filter{session.canShow(it)}.filter{c->when(c.format){AdvertisingFormat.COMPACT_BANNER->configuration.compactBannersEnabled;AdvertisingFormat.SPONSORED_CARD->configuration.sponsoredCardsEnabled;AdvertisingFormat.BACKGROUND_AD->configuration.backgroundAdsEnabled&&preferences.backgroundAdsEnabled}}.sortedWith(compareByDescending<SponsoredCampaign>{it.priority}.thenBy{it.id}).firstOrNull()
}
interface AdvertisingAnalytics{fun recordImpression(campaignId:String,placement:AdPlacement,format:AdvertisingFormat,activityType:MarineActivityType?,destinationId:String?);fun recordClick(campaignId:String,placement:AdPlacement,format:AdvertisingFormat,activityType:MarineActivityType?,destinationId:String?);fun recordDismiss(campaignId:String,placement:AdPlacement,format:AdvertisingFormat);fun recordBackgroundOpacityChanged(oldValue:Float,newValue:Float)}
object NoOpAdvertisingAnalytics:AdvertisingAnalytics{override fun recordImpression(campaignId:String,placement:AdPlacement,format:AdvertisingFormat,activityType:MarineActivityType?,destinationId:String?){};override fun recordClick(campaignId:String,placement:AdPlacement,format:AdvertisingFormat,activityType:MarineActivityType?,destinationId:String?){};override fun recordDismiss(campaignId:String,placement:AdPlacement,format:AdvertisingFormat){};override fun recordBackgroundOpacityChanged(oldValue:Float,newValue:Float){}}
interface AdNetworkProvider{fun isAvailable():Boolean;fun loadBanner(placement:AdPlacement);fun dispose()}
