package bg.blacksea.buoys.ui

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.clickable
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import bg.blacksea.buoys.MainViewModel
import bg.blacksea.buoys.domain.*
import bg.blacksea.buoys.forecast.*
import bg.blacksea.buoys.ui.activities.ActivitiesScreen
import bg.blacksea.buoys.ui.activities.ActivityCriteriaContext
import bg.blacksea.buoys.advertising.*
import bg.blacksea.buoys.domain.swell.*
import bg.blacksea.buoys.domain.activity.UserActivityProfilesRuntime
import bg.blacksea.buoys.ui.advertising.SponsoredCompactBanner
import java.time.ZoneId
import java.time.format.DateTimeFormatter

@Composable fun BuoysApp(vm:MainViewModel){
    val appLanguage by vm.appLanguage.collectAsState()
    AppLanguage.code=appLanguage
    val selectedHistory by vm.selectedHistory.collectAsState()
    val atmospheric by vm.atmospheric.collectAsState()
    val activitiesDaylightOnly by vm.activitiesDaylightOnly.collectAsState();val defaultActivityExperience by vm.defaultActivityExperience.collectAsState()
    val onboardingComplete by vm.onboardingComplete.collectAsState()
    val userActivityProfiles by vm.userActivityProfiles.collectAsState()
    ActivityCriteriaContext.profiles=userActivityProfiles;ActivityCriteriaContext.save=vm::saveActivityProfile;ActivityCriteriaContext.reset=vm::resetActivityProfile
    UserActivityProfilesRuntime.profiles=userActivityProfiles
    val snap by vm.snapshot.collectAsState(); val selected by vm.selected.collectAsState(); val fav by vm.favorites.collectAsState(); val activityFav by vm.activityFavorites.collectAsState(); val forecast by vm.forecast.collectAsState(); val refreshMinutes by vm.refreshMinutes.collectAsState();val allAds by vm.allAdsEnabled.collectAsState();val bgAds by vm.backgroundAdsEnabled.collectAsState();val adOpacity by vm.backgroundAdOpacity.collectAsState();val adState by vm.advertising.collectAsState();val adSession=remember{AdvertisingSession()};val adPrefs=UserAdvertisingPreferences(allAdsEnabled=allAds,backgroundAdsEnabled=bgAds,backgroundOpacity=adOpacity);val forecastBanner=remember(adState,selected,allAds){selectCampaign(adState.campaigns,adState.configuration,adPrefs,AdPlacement.FORECAST_BOTTOM,vm.forecastDestinationId(selected),session=adSession)};LaunchedEffect(forecastBanner?.id){forecastBanner?.let(adSession::record)}; var tab by remember{mutableIntStateOf(0)};var forecastMode by remember{mutableStateOf(false)}
    MaterialTheme(colorScheme=if(isSystemInDarkTheme()) darkColorScheme() else lightColorScheme(primary=Color(0xFF006D77),secondary=Color(0xFF0A9396))){
        Scaffold(topBar={if(tab==0)LanguageBar(appLanguage,vm::setLanguage)},bottomBar={NavigationBar{listOf((if(appLanguage=="en")"Home" else "Начало") to Icons.Default.Home,(if(appLanguage=="en")"Sports" else "Спортове") to Icons.Default.Waves,(if(appLanguage=="en")"Favorites" else "Любими") to Icons.Default.Favorite,(if(appLanguage=="en")"Settings" else "Настройки") to Icons.Default.Settings).forEachIndexed{i,(t,icon)->NavigationBarItem(selected=tab==i,onClick={tab=i;if(i==1)vm.refreshForecast()},icon={Icon(icon,null)},label={Text(t)})}}}){pad->
            Box(Modifier.padding(pad)){when(tab){0->Column{SingleChoiceSegmentedButtonRow(Modifier.padding(16.dp,8.dp).fillMaxWidth()){SegmentedButton(!forecastMode,{forecastMode=false},SegmentedButtonDefaults.itemShape(0,2)){Text(tr("Измервания","Measurements"))};SegmentedButton(forecastMode,{forecastMode=true;vm.refreshForecast()},SegmentedButtonDefaults.itemShape(1,2)){Text(tr("Прогноза","Forecast"))}};if(forecastMode)ForecastScreen(forecast,atmospheric,vm.destinations,vm.forecastDestinationId(selected),vm::select,vm::refreshForecast,forecastBanner){c->vm.dismissAd(c.id,c.dismissDurationHours)}else Home(snap.observations.distinctBy{it.stationId},selected,fav,snap.refreshing,snap.error,selectedHistory,atmospheric,vm::select,vm::favorite,vm::refresh)};1->ActivitiesScreen(vm.forecastDestinationName(selected),vm.forecastDestinationId(selected),snap.observations.firstOrNull{it.stationId==selected}?:snap.observations.firstOrNull(),forecast.points,atmospheric.forecast,activityFav,vm::toggleActivityFavorite);2->Favorites(snap.observations.filter{it.stationId in fav}.distinctBy{it.stationId},vm::select){tab=0};else->Settings(refreshMinutes,vm::setRefreshMinutes,allAds,bgAds,adOpacity,activitiesDaylightOnly,defaultActivityExperience,vm::setAllAds,vm::setBackgroundAds,vm::setAdOpacity,vm::setActivitiesDaylightOnly,vm::setDefaultActivityExperience,vm::resetActivitySettings)}}
        }
        if(!onboardingComplete)OnboardingGuide(vm::completeOnboarding)
    }
}

@Composable private fun OnboardingGuide(finish:()->Unit){var page by remember{mutableIntStateOf(0)};val pages=listOf(Triple("🌊",tr("Добре дошли","Welcome"),tr("Следете актуалните измервания и прогнозата за избраната морска станция.","Track current observations and forecasts for the selected marine station.")),Triple("📈",tr("Измервания и графики","Measurements and charts"),tr("Плъзнете екрана нагоре, за да видите историята за море, вълни, вятър и интервал. Под всяка група е посочен източникът.","Scroll up to view sea, wave, wind and interval history. Each group shows its data source.")),Triple("🏄",tr("Морски спортове","Marine sports"),tr("Цветът е ориентировъчна оценка по различни критерии за всеки спорт. Дневните активности използват изгрев и залез; оценката не е гаранция за безопасност.","Colors are indicative ratings based on sport-specific criteria. Daytime activities use sunrise and sunset; ratings are not a safety guarantee.")),Triple("🎚",tr("Вашите критерии","Your criteria"),tr("От подробностите на спорта можете да настройвате лимити, ниво на опит и часовете за оценка. Винаги проверявайте местните предупреждения.","From sport details you can adjust limits, experience and evaluation hours. Always check local warnings.")));val current=pages[page];AlertDialog(onDismissRequest={},icon={Text(current.first,fontSize=42.sp)},title={Text(current.second)},text={Column(verticalArrangement=Arrangement.spacedBy(12.dp)){Text(current.third);LinearProgressIndicator(progress={(page+1)/pages.size.toFloat()},modifier=Modifier.fillMaxWidth());Text("${page+1}/${pages.size}",style=MaterialTheme.typography.labelSmall)}},confirmButton={Button(onClick={if(page<pages.lastIndex)page++ else finish()}){Text(if(page<pages.lastIndex)tr("Напред","Next")else tr("Започни","Start"))}},dismissButton={if(page>0)TextButton(onClick={page--}){Text(tr("Назад","Back"))}else TextButton(onClick=finish){Text(tr("Пропусни","Skip"))}})}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun LanguageBar(language:String,setLanguage:(String)->Unit){
    var expanded by remember{mutableStateOf(false)}
    TopAppBar(title={Text(if(language=="en")"Black Sea" else "Черно море",fontWeight=FontWeight.Bold)},actions={Box{IconButton(onClick={expanded=true}){Icon(Icons.Default.Language,if(language=="en")"Change language" else "Смяна на езика")};DropdownMenu(expanded=expanded,onDismissRequest={expanded=false}){DropdownMenuItem(text={Text("🇧🇬 Български")},leadingIcon={if(language=="bg")Icon(Icons.Default.Check,null)},onClick={setLanguage("bg");expanded=false});DropdownMenuItem(text={Text("🇬🇧 English")},leadingIcon={if(language=="en")Icon(Icons.Default.Check,null)},onClick={setLanguage("en");expanded=false})}}})
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun ForecastScreen(state:ForecastState,atmospheric:AtmosphericForecastState,destinations:List<ForecastDestination>,selected:String,select:(String)->Unit,refresh:()->Unit,banner:SponsoredCampaign?=null,dismiss:(SponsoredCampaign)->Unit={}){
    var choose by remember{mutableStateOf(false)};var period by remember{mutableIntStateOf(1)};var selectedDate by remember{mutableStateOf<java.time.LocalDate?>(null)};val destination=destinations.firstOrNull{it.id==selected}?:destinations.first{it.id=="varna"};val next=state.points.nearestFuture()?:state.points.firstOrNull();val days=state.points.days();val visibleDays=days.take(period);val activeDay=selectedDate?.let{date->visibleDays.firstOrNull{it.date==date}}?:visibleDays.firstOrNull();val hourly=if(period==1)state.points.filter{!it.forecastAt.isBefore(java.time.Instant.now())}.take(24)else activeDay?.points.orEmpty()
    LaunchedEffect(destination.id){refresh()}
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=16.dp,vertical=4.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
        Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(destination.name,fontSize=24.sp,fontWeight=FontWeight.Bold);Text("ПРОГНОЗНИ ДАННИ",color=MaterialTheme.colorScheme.primary,fontWeight=FontWeight.Bold)};OutlinedButton(onClick={choose=true}){Icon(Icons.Default.Place,null);Spacer(Modifier.width(6.dp));Text("Смени")};IconButton(onClick=refresh){Icon(Icons.Default.Refresh,"Обнови")}}
        Text("Източник: Open-Meteo Marine • прогнозна стойност",style=MaterialTheme.typography.bodySmall)
        if(state.loading)LinearProgressIndicator(Modifier.fillMaxWidth());state.error?.let{Text(it,color=MaterialTheme.colorScheme.error)}
        next?.let{ForecastMain(it,destination.name,atmospheric.forecast)}?:ElevatedCard(Modifier.fillMaxWidth()){Text("Няма налична прогноза. Натиснете „Обнови“.",Modifier.padding(20.dp))}
        if(state.points.isNotEmpty()){
            SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){listOf(1 to "24 часа",3 to "3 дни",7 to "7 дни").forEachIndexed{i,(value,label)->SegmentedButton(period==value,{period=value;selectedDate=null},SegmentedButtonDefaults.itemShape(i,3)){Text(label)}}}
            if(period>1){LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(visibleDays){day->ForecastDayCard(day,atmospheric.forecast,activeDay?.date==day.date){selectedDate=day.date}}}}
            Text(if(period==1)"Следващите 24 часа" else "Почасово за ${activeDay?.date?.format(DateTimeFormatter.ofPattern("dd.MM"))?:"избрания ден"}",fontWeight=FontWeight.Bold)
            LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(hourly){ForecastHour(it,atmospheric.forecast)}}
            if(period>1){Text("Обобщение",fontWeight=FontWeight.Bold);visibleDays.forEach{ForecastDayRow(it,atmospheric.forecast)}}
            banner?.let{Spacer(Modifier.height(8.dp));SponsoredCompactBanner(it,{dismiss(it)})}
        }
    }
    if(choose)ModalBottomSheet(onDismissRequest={choose=false}){Text("Избери дестинация",Modifier.padding(20.dp),fontSize=22.sp,fontWeight=FontWeight.Bold);destinations.forEach{d->ListItem(headlineContent={Text(d.name)},modifier=Modifier.clickable{select(d.id);choose=false})};Spacer(Modifier.height(20.dp))}
}
@Composable private fun ForecastMain(p:MarineForecastPoint,name:String,weather:AtmosphericForecast?){val air=weather?.hourly?.minByOrNull{kotlin.math.abs(it.time.epochSecond-p.forecastAt.epochSecond)};ElevatedCard(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(p.forecastAt.atZone(ZoneId.of("Europe/Sofia")).format(DateTimeFormatter.ofPattern("dd.MM, HH:mm")));Row{Metric(tr("Температура на въздуха","Air temperature"),air?.airTemperatureCelsius?.let{"%.1f °C".format(it)}?:"—",Modifier.weight(1f));Metric(tr("Температура на морето","Sea temperature"),p.seaSurfaceTemperatureC?.let{"%.1f °C".format(it)}?:"—",Modifier.weight(1f))};Text("${tr("Вълни","Waves")}: ${p.waveHeightM?.let{"%.2f m".format(it)}?:"—"}");Text("${tr("Интервал между вълните","Wave interval")}: ${p.wavePeriodS?.let{"%.1f s".format(it)}?:"—"}  •  ${tr("Посока","Direction")}: ${p.waveDirectionDeg?.let{"${it.toInt()}° ${degreesToCompassDirection(it)}"}?:"—"}");SwellIndicator(p);Text(tr("Източник: Open-Meteo Marine и Open-Meteo Weather","Source: Open-Meteo Marine and Open-Meteo Weather"),style=MaterialTheme.typography.labelSmall);Text("${tr("Моделни данни, обновени","Model data updated")}: ${p.fetchedAt.atZone(ZoneId.of("Europe/Sofia")).format(DateTimeFormatter.ofPattern("dd.MM.yyyy, HH:mm"))}",style=MaterialTheme.typography.labelSmall)}}}
@Composable private fun ForecastHour(p:MarineForecastPoint,weather:AtmosphericForecast?){val local=p.forecastAt.atZone(ZoneId.of("Europe/Sofia"));val day=local.hour in 7..19;val background=if(day)Color(0xFFFFF1CC)else Color(0xFF24324A);val content=if(day)Color(0xFF292316)else Color(0xFFF2F5FA);val air=weather?.hourly?.minByOrNull{kotlin.math.abs(it.time.epochSecond-p.forecastAt.epochSecond)};ElevatedCard(Modifier.width(132.dp),colors=CardDefaults.elevatedCardColors(containerColor=background,contentColor=content)){Column(Modifier.padding(10.dp),verticalArrangement=Arrangement.spacedBy(3.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(local.format(DateTimeFormatter.ofPattern("HH:mm")),fontWeight=FontWeight.Bold);Text(if(day)"☀" else "☾",fontSize=18.sp)};Text("${tr("Въздух","Air")} ${air?.airTemperatureCelsius?.let{"%.1f °C".format(it)}?:"—"}");Text("${tr("Море","Sea")} ${p.seaSurfaceTemperatureC?.let{"%.1f °C".format(it)}?:"—"}");Text("${tr("Вълни","Waves")} ${p.waveHeightM?.let{"%.1f m".format(it)}?:"—"}");Text("${tr("Интервал","Interval")} ${p.wavePeriodS?.let{"%.1f s".format(it)}?:"—"}")}}}
@Composable private fun ForecastDayCard(d:MarineForecastDay,weather:AtmosphericForecast?,selected:Boolean,onClick:()->Unit){val zone=ZoneId.of("Europe/Sofia");val daily=weather?.daily?.firstOrNull{it.date==d.date};val hours=weather?.hourly.orEmpty().filter{it.time.atZone(zone).toLocalDate()==d.date};val sunrise=daily?.sunrise;val sunset=daily?.sunset;val daytime=hours.filter{h->if(sunrise!=null&&sunset!=null)(!h.time.isBefore(sunrise)&&h.time.isBefore(sunset)) else h.time.atZone(zone).hour in 7..19}.mapNotNull{it.airTemperatureCelsius};val nighttime=hours.filter{h->if(sunrise!=null&&sunset!=null)(h.time.isBefore(sunrise)||!h.time.isBefore(sunset)) else h.time.atZone(zone).hour !in 7..19}.mapNotNull{it.airTemperatureCelsius};val dayRange=formatTemperatureRange(daytime);val nightRange=formatTemperatureRange(nighttime);Card(onClick=onClick,colors=CardDefaults.cardColors(containerColor=if(selected)MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.width(170.dp)){Column(Modifier.padding(10.dp),verticalArrangement=Arrangement.spacedBy(2.dp)){Text(d.date.format(DateTimeFormatter.ofPattern("EEE dd.MM")),fontWeight=FontWeight.Bold);Text(d.maximumWaveHeightM?.let{"${tr("Вълни до","Waves up to")} %.1f m".format(it)}?:tr("Няма данни","No data"),style=MaterialTheme.typography.bodySmall);Text("${tr("Ден","Day")}: $dayRange",style=MaterialTheme.typography.bodySmall);Text("${tr("Нощ","Night")}: $nightRange",style=MaterialTheme.typography.bodySmall);Text("${tr("Море","Sea")}: ${d.minimumSeaTemperatureC?.let{"%.0f".format(it)}?:"—"}–${d.maximumSeaTemperatureC?.let{"%.0f °C".format(it)}?:"—"}",style=MaterialTheme.typography.bodySmall)}}}
private fun formatTemperatureRange(values:List<Double>)=if(values.isEmpty())"—" else "%.0f–%.0f °C".format(values.min(),values.max())
@Composable private fun ForecastDayRow(d:MarineForecastDay,weather:AtmosphericForecast?){val air=weather?.daily?.firstOrNull{it.date==d.date};ElevatedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(3.dp)){Text(d.date.format(DateTimeFormatter.ofPattern("EEE, dd.MM")),fontWeight=FontWeight.Bold);Text("${tr("Въздух","Air")}: ${air?.minimumAirTemperatureCelsius?.let{"%.0f".format(it)}?:"—"}–${air?.maximumAirTemperatureCelsius?.let{"%.0f °C".format(it)}?:"—"}");Text("${tr("Море","Sea")}: ${d.minimumSeaTemperatureC?.let{"%.1f".format(it)}?:"—"}–${d.maximumSeaTemperatureC?.let{"%.1f °C".format(it)}?:"—"}");Text("${tr("Вълни до","Waves up to")} ${d.maximumWaveHeightM?.let{"%.1f m".format(it)}?:"—"} • ${tr("Интервал","Interval")} ${d.averageWavePeriodS?.let{"%.1f s".format(it)}?:"—"}",style=MaterialTheme.typography.bodySmall);Text(tr("Източник: Open-Meteo · прогнозни данни","Source: Open-Meteo · forecast data"),style=MaterialTheme.typography.labelSmall)}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun SwellIndicator(p:MarineForecastPoint){val assessment=remember(p){DefaultSwellConditionEvaluator().evaluate(SwellConditionInput(p.swellWaveHeightM,p.swellWavePeriodS,p.swellWaveDirectionDeg,p.waveHeightM,p.wavePeriodS,p.windWaveHeightM,dataAge=java.time.Duration.between(p.fetchedAt,java.time.Instant.now()),hasOfficialWarning=false))};var details by remember{mutableStateOf(false)};val color=when(assessment.level){SwellConditionLevel.LOW->Color(0xFF5F7D6A);SwellConditionLevel.MODERATE->Color(0xFFB7791F);SwellConditionLevel.ELEVATED->Color(0xFFD97706);SwellConditionLevel.UNAVAILABLE->Color.Gray};Surface(onClick={details=true},color=color.copy(alpha=.12f),shape=RoundedCornerShape(10.dp),modifier=Modifier.fillMaxWidth().semantics{contentDescription=tr("Ориентировъчна оценка на условията за мъртво вълнение","Indicative swell conditions assessment")}){Text("~ ${assessment.summary}",Modifier.padding(10.dp),color=color,style=MaterialTheme.typography.bodySmall)};if(details)ModalBottomSheet(onDismissRequest={details=false}){Column(Modifier.padding(20.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(tr("Условия за мъртво вълнение","Swell conditions"),fontSize=22.sp,fontWeight=FontWeight.Bold);Text(tr("Ориентировъчна оценка","Indicative assessment"),color=color,fontWeight=FontWeight.Bold);Text(assessment.summary);Text(tr("Използвани показатели","Indicators used"),fontWeight=FontWeight.Bold);assessment.details.forEach{Text("• $it")};Text(tr("Мъртвото вълнение се формира далеч от брега и може да достига крайбрежието дори когато местният вятър не е силен.","Swell forms far offshore and can reach the coast even when local wind is weak."));Text(tr("Оценката е ориентировъчна. Местните течения и условията на конкретния плаж могат да се различават. Проверявайте спасителните флагове и указанията на място.","This is an indicative assessment. Local currents and beach conditions may differ. Check lifeguard flags and local guidance."),style=MaterialTheme.typography.bodySmall);Text(tr("Прогноза: Open-Meteo Marine","Forecast: Open-Meteo Marine"),style=MaterialTheme.typography.labelSmall);TextButton(onClick={details=false}){Text(tr("Затвори","Close"))};Spacer(Modifier.height(20.dp))}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun Home(items:List<BuoyObservation>,selected:String,favorites:List<String>,loading:Boolean,error:String?,history:List<BuoyObservation>,atmospheric:AtmosphericForecastState,select:(String)->Unit,favorite:(String)->Unit,refresh:()->Unit){
    var choose by remember{mutableStateOf(false)}; val item=items.firstOrNull{it.stationId==selected}?:items.firstOrNull()
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
        Row(verticalAlignment=Alignment.CenterVertically){Text(item?.stationName?:tr("Няма избрана станция","No station selected"),fontSize=25.sp,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));IconButton(onClick={choose=true}){Icon(Icons.Default.Place,tr("Смяна","Change"))};IconButton(onClick=refresh){Icon(Icons.Default.Refresh,tr("Обнови","Refresh"))}}
        if(loading) LinearProgressIndicator(Modifier.fillMaxWidth()); error?.let{AssistChip(onClick={},label={Text(if(item!=null)tr("Временно няма връзка. Показват се запазените измервания.","Temporarily offline. Showing saved measurements.") else it)},leadingIcon={Icon(Icons.Default.Warning,null)})}
        item?.let{ObservationCard(it,history,atmospheric,it.stationId in favorites,{favorite(it.stationId)})}?:EmptyState()
        Text(tr("Последни станции","Latest stations"),fontWeight=FontWeight.SemiBold);Column(verticalArrangement=Arrangement.spacedBy(8.dp)){items.forEach{o->StationRow(o,o.stationId in favorites,{select(o.stationId)},{favorite(o.stationId)})}};Spacer(Modifier.height(12.dp))
    }
    if(choose) ModalBottomSheet(onDismissRequest={choose=false}){Text(tr("Избор на дестинация","Choose destination"),Modifier.padding(20.dp),fontSize=22.sp,fontWeight=FontWeight.Bold);items.forEach{o->ListItem(headlineContent={Text(o.stationName)},supportingContent={Text(tr("Наблюдателна станция","Observation station"))},modifier=Modifier.clickable{select(o.stationId);choose=false})};Spacer(Modifier.height(24.dp))}
}

@Composable private fun ObservationCard(o:BuoyObservation,history:List<BuoyObservation>,atmospheric:AtmosphericForecastState,favorite:Boolean,toggle:()->Unit){
    ElevatedCard(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
        Row{Metric(tr("Температура на въздуха","Air temperature"),atmospheric.forecast?.currentAirTemperatureCelsius?.let{"%.1f °C".format(it)}?:"—",Modifier.weight(1f));Metric(tr("Температура на морето","Sea temperature"),o.waterTemperatureC?.let{"%.1f °C".format(it)}?:"—",Modifier.weight(1f));IconButton(onClick=toggle){Icon(if(favorite)Icons.Default.Favorite else Icons.Default.FavoriteBorder,tr("Любима","Favorite"))}}
        Text("${tr("Вълни","Waves")}: ${o.significantWaveHeightM?.let{"%.2f m".format(it)}?:"—"}",fontWeight=FontWeight.SemiBold)
        HorizontalDivider();Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Row(Modifier.fillMaxWidth()){Small("Hmax",o.maximumWaveHeightM?.let{"$it m"}?:"—",Modifier.weight(1f));Small(tr("Интервал на вълните","Wave interval"),o.wavePeriodS?.let{"$it s"}?:"—",Modifier.weight(1f))};Row(Modifier.fillMaxWidth()){Small(tr("Посока","Direction"),o.waveDirectionDeg?.let{"${it.toInt()}° ${compass(it)}"}?:"—",Modifier.weight(1f));Small(tr("Вятър","Wind"),o.windSpeedMs?.let{"$it m/s"}?:"—",Modifier.weight(1f))}}
        MeasurementCharts(history.ifEmpty{listOf(o)})
        Text("${tr("Измерено","Measured")}: ${o.measuredAtUtc?.atZone(ZoneId.of("Europe/Sofia"))?.format(DateTimeFormatter.ofPattern("dd.MM.yyyy, HH:mm"))?:tr("няма дата","no date")}",style=MaterialTheme.typography.bodySmall)
        Text("${tr("Източник","Source")}: ${tr("Морска станция","Marine station")} ${o.stationName}",style=MaterialTheme.typography.labelSmall)
        Text("${tr("Температура на въздуха – прогноза","Air temperature – forecast")}: Open-Meteo Weather · ${atmospheric.forecast?.fetchedAt?.atZone(ZoneId.of("Europe/Sofia"))?.format(DateTimeFormatter.ofPattern("HH:mm"))?:"—"}",style=MaterialTheme.typography.labelSmall)
        val status=freshness(o.measuredAtUtc, cached=o.isCached);Text(freshnessTitle(status),color=when(status){Freshness.CURRENT->Color(0xFF198754);Freshness.STALE->Color(0xFFE09F00);else->MaterialTheme.colorScheme.error},fontWeight=FontWeight.Bold)
    }}
}
@Composable private fun Metric(label:String,value:String,modifier:Modifier){Column(modifier){Text(label,style=MaterialTheme.typography.labelMedium);Text(value,fontSize=30.sp,fontWeight=FontWeight.Bold)}}
@Composable private fun Small(label:String,value:String,modifier:Modifier=Modifier){Column(modifier,horizontalAlignment=Alignment.CenterHorizontally){Text(label,style=MaterialTheme.typography.labelSmall,maxLines=2);Text(value,fontWeight=FontWeight.SemiBold)}}
@Composable private fun StationRow(o:BuoyObservation,fav:Boolean,open:()->Unit,toggle:()->Unit){ElevatedCard(Modifier.fillMaxWidth().clickable(onClick=open)){ListItem(headlineContent={Text(o.stationName)},supportingContent={Text("${o.waterTemperatureC?:"—"} °C  •  ${o.significantWaveHeightM?:"—"} m")},trailingContent={IconButton(onClick=toggle){Icon(if(fav)Icons.Default.Favorite else Icons.Default.FavoriteBorder,null)}})}}
@Composable private fun Favorites(items:List<BuoyObservation>,select:(String)->Unit,open:()->Unit){Column(Modifier.padding(16.dp)){Text(tr("Любими","Favorites"),fontSize=26.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(12.dp));if(items.isEmpty())Text(tr("Добавете станции с иконата сърце.","Add stations using the heart icon.")) else LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){items(items){StationRow(it,true,{select(it.stationId);open()},{})}}}}
@Composable private fun Settings(refreshMinutes:Int,setRefresh:(Int)->Unit,allAds:Boolean,bgAds:Boolean,opacity:Float,daylightOnly:Boolean,experience:String,setAllAds:(Boolean)->Unit,setBgAds:(Boolean)->Unit,setOpacity:(Float)->Unit,setDaylightOnly:(Boolean)->Unit,setExperience:(String)->Unit,resetActivities:()->Unit){val choices=listOf(15 to "15 мин",30 to "30 мин",60 to "1 час",180 to "3 часа",0 to "Ръчно");Column(Modifier.padding(16.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(12.dp)){Text(tr("Настройки","Settings"),fontSize=26.sp,fontWeight=FontWeight.Bold);Text(tr("Автоматично обновяване","Automatic refresh"));Column(verticalArrangement=Arrangement.spacedBy(6.dp)){choices.forEach{(minutes,label)->FilterChip(selected=refreshMinutes==minutes,onClick={setRefresh(minutes)},label={Text(label)},leadingIcon=if(refreshMinutes==minutes){{Icon(Icons.Default.Check,null)}}else null,modifier=Modifier.fillMaxWidth())}};HorizontalDivider();Text(tr("Морски активности","Marine activities"),fontWeight=FontWeight.Bold);Row(verticalAlignment=Alignment.CenterVertically){Text(tr("Оценявай дневните спортове само през светлата част","Evaluate daytime sports only during daylight"),Modifier.weight(1f));Switch(daylightOnly,setDaylightOnly)};Text(tr("Ниво на опит по подразбиране","Default experience level"));SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){listOf("BEGINNER" to tr("Начинаещ","Beginner"),"INTERMEDIATE" to tr("Средно","Intermediate"),"ADVANCED" to tr("Напреднал","Advanced")).forEachIndexed{i,(value,label)->SegmentedButton(experience==value,{setExperience(value)},SegmentedButtonDefaults.itemShape(i,3)){Text(label,maxLines=1)}}};OutlinedButton(onClick=resetActivities,modifier=Modifier.fillMaxWidth()){Text(tr("Възстанови спортните настройки","Reset activity settings"))};Text(tr("Фабричните прагове са ориентировъчни продуктови настройки, не гаранция за безопасност.","Factory thresholds are indicative product settings, not a safety guarantee."),style=MaterialTheme.typography.bodySmall);HorizontalDivider();Text(tr("Реклами и партньори","Ads and partners"),fontWeight=FontWeight.Bold);Row(verticalAlignment=Alignment.CenterVertically){Text(tr("Разреши реклами","Allow ads"),Modifier.weight(1f));Switch(allAds,setAllAds)};Row(verticalAlignment=Alignment.CenterVertically){Text(tr("Фонова реклама","Background ad"),Modifier.weight(1f));Switch(bgAds&&allAds,{setBgAds(it)},enabled=allAds)};Text("${tr("Прозрачност","Opacity")}: ${(opacity*100).toInt()}%",style=MaterialTheme.typography.bodySmall);Slider(opacity,setOpacity,valueRange=.03f..20f/100f,enabled=allAds&&bgAds);HorizontalDivider();Text("${tr("Източник","Source")}: mm.meteo-varna.net",style=MaterialTheme.typography.bodySmall);Spacer(Modifier.height(16.dp))}}
@Composable private fun EmptyState(){Box(Modifier.fillMaxWidth().height(220.dp),contentAlignment=Alignment.Center){Text("Няма налични измервания.")}}
@Composable private fun MeasurementCharts(observations:List<BuoyObservation>){val ordered=observations.filter{it.measuredAtUtc!=null}.distinctBy{it.measuredAtUtc}.sortedBy{it.measuredAtUtc}.takeLast(4);if(ordered.isEmpty())return;HorizontalDivider();Text(tr("Графики на измерванията","Measurement charts"),fontWeight=FontWeight.SemiBold,style=MaterialTheme.typography.bodyMedium);ElevatedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){MeasurementChart(tr("Температура на морето","Sea temperature"),"°C",ordered.mapNotNull{o->o.waterTemperatureC?.let{o.measuredAtUtc!! to it}},1);HorizontalDivider();MeasurementChart(tr("Височина на вълните","Wave height"),"m",ordered.mapNotNull{o->o.significantWaveHeightM?.let{o.measuredAtUtc!! to it}},2);HorizontalDivider();MeasurementChart(tr("Скорост на вятъра","Wind speed"),"m/s",ordered.mapNotNull{o->o.windSpeedMs?.let{o.measuredAtUtc!! to it}},1);HorizontalDivider();MeasurementChart(tr("Интервал между вълните","Wave interval"),"s",ordered.mapNotNull{o->o.wavePeriodS?.let{o.measuredAtUtc!! to it}},1)}}}
@Composable private fun MeasurementChart(title:String,unit:String,points:List<Pair<java.time.Instant,Double>>,decimals:Int){Column(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(title,fontWeight=FontWeight.Bold);if(points.isEmpty()){Text(tr("Няма измерени данни","No measured data"),modifier=Modifier.height(40.dp))}else{Row(Modifier.fillMaxWidth()){points.forEach{(_,v)->Text("%.${decimals}f %s".format(v,unit),color=Color(0xFF0A9396),fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelMedium,textAlign=androidx.compose.ui.text.style.TextAlign.Center,modifier=Modifier.weight(1f))}};Canvas(Modifier.fillMaxWidth().height(48.dp)){val values=points.map{it.second};val low=(values.minOrNull()?:0.0);val high=(values.maxOrNull()?:1.0);val margin=((high-low)*.15).coerceAtLeast(.1);val range=(high-low+margin*2).coerceAtLeast(.2);val path=Path();points.forEachIndexed{i,p->val x=(i+.5f)*size.width/points.size;val y=size.height-6f-(((p.second-(low-margin))/range).toFloat()*(size.height-12f));if(i==0)path.moveTo(x,y)else path.lineTo(x,y);drawCircle(Color(0xFF006D77),5f,Offset(x,y))};drawPath(path,Color(0xFF0A9396),style=androidx.compose.ui.graphics.drawscope.Stroke(3f))};Row(Modifier.fillMaxWidth()){points.forEach{(time,_)->Text(time.atZone(ZoneId.of("Europe/Sofia")).format(DateTimeFormatter.ofPattern("HH:mm")),style=MaterialTheme.typography.labelSmall,textAlign=androidx.compose.ui.text.style.TextAlign.Center,modifier=Modifier.weight(1f))}}}}}
