package bg.blacksea.buoys.ui.activities

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import bg.blacksea.buoys.domain.activity.*
import bg.blacksea.buoys.ui.AppLanguage
import bg.blacksea.buoys.ui.activityTitle
import bg.blacksea.buoys.ui.tr
import java.time.LocalTime

object ActivityCriteriaContext{var profiles:Map<MarineActivityType,UserActivityProfile> = emptyMap();var save:(UserActivityProfile)->Unit={};var reset:(MarineActivityType)->Unit={}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun ActivityCriteriaEditor(activity:MarineActivityType,saved:UserActivityProfile?,save:(UserActivityProfile)->Unit,reset:()->Unit,close:()->Unit){
 val factory=ActivityProfileFactory.default(activity);var profile by remember(activity,saved){mutableStateOf(saved?:UserActivityProfile(activity,timeMode=factory.timePolicy.defaultMode,thresholds=factory.thresholds))};var dirty by remember{mutableStateOf(false)};var confirmClose by remember{mutableStateOf(false)}
 fun change(p:UserActivityProfile){profile=p.copy(experienceLevel=ExperienceLevel.CUSTOM,useFactoryDefaults=false);dirty=true}
 ModalBottomSheet(onDismissRequest={if(dirty)confirmClose=true else close()}){Column(Modifier.fillMaxSize()){Column(Modifier.weight(1f).verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Text("${tr("Критерии за","Criteria for")} ${activityTitle(activity)}",style=MaterialTheme.typography.headlineSmall);Text(tr("Настройте личните си ориентировъчни граници. Официалните предупреждения винаги имат приоритет.","Set your personal indicative limits. Official warnings always take priority."),style=MaterialTheme.typography.bodySmall)
  Text(tr("Ниво на опит","Experience level"),style=MaterialTheme.typography.titleMedium);ExperienceLevel.entries.forEach{level->Row{RadioButton(profile.experienceLevel==level,{profile=profile.copy(experienceLevel=level,thresholds=if(level==ExperienceLevel.CUSTOM)profile.thresholds else factory.thresholds,useFactoryDefaults=level!=ExperienceLevel.CUSTOM);dirty=true});Text(when(level){ExperienceLevel.BEGINNER->tr("Начинаещ","Beginner");ExperienceLevel.INTERMEDIATE->tr("Средно напреднал","Intermediate");ExperienceLevel.ADVANCED->tr("Напреднал","Advanced");ExperienceLevel.CUSTOM->tr("Собствени настройки","Custom")},Modifier.padding(top=12.dp))}}
  Text(tr("Часове за оценка","Evaluation hours"),style=MaterialTheme.typography.titleMedium);ActivityTimeMode.entries.forEach{mode->Row{RadioButton(profile.timeMode==mode,{profile=profile.copy(timeMode=mode);dirty=true});Text(when(mode){ActivityTimeMode.DAYLIGHT_ONLY->tr("Само през светлата част","Daylight only");ActivityTimeMode.DAY_AND_NIGHT->tr("Ден и нощ","Day and night");ActivityTimeMode.CUSTOM_TIME_WINDOW->tr("Собствен часови диапазон","Custom time window")},Modifier.padding(top=12.dp))}}
  if(profile.timeMode==ActivityTimeMode.CUSTOM_TIME_WINDOW)Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){TimeField(tr("Начало","Start"),profile.customStartTime?:LocalTime.of(7,0),Modifier.weight(1f)){profile=profile.copy(customStartTime=it);dirty=true};TimeField(tr("Край","End"),profile.customEndTime?:LocalTime.of(19,0),Modifier.weight(1f)){profile=profile.copy(customEndTime=it);dirty=true}}
  ActivityCriterionDefinitions.forActivity(activity).forEach{d->val range=profile.thresholds.range(d.parameter)?:d.factoryRange?:NumericRange(d.controlMinimum,d.controlMaximum);CriterionRangeEditor(if(AppLanguage.code=="bg")d.titleBg else d.titleEn,range.minimum?:d.controlMinimum,range.maximum?:d.controlMaximum,d.controlMinimum,d.controlMaximum,d.step,d.unit,if(AppLanguage.code=="bg")d.supportingBg else d.supportingEn,null,{min,max->change(profile.copy(thresholds=profile.thresholds.withRange(d.parameter,NumericRange(min,max))))},{change(profile.copy(thresholds=profile.thresholds.withRange(d.parameter,d.factoryRange!!)))})}
  OutlinedButton(onClick={profile=UserActivityProfile(activity,timeMode=factory.timePolicy.defaultMode,thresholds=factory.thresholds);dirty=true;reset()},Modifier.fillMaxWidth()){Text(tr("Възстанови препоръчителните стойности","Restore recommended values"))};Card{Column(Modifier.padding(12.dp)){Text(tr("Преглед","Preview"),style=MaterialTheme.typography.titleMedium);Text(tr("Оценката ще се преизчисли веднага след запазване.","The rating will be recalculated immediately after saving."))}}}
  Surface(shadowElevation=8.dp){Row(Modifier.fillMaxWidth().padding(12.dp),horizontalArrangement=Arrangement.spacedBy(12.dp)){OutlinedButton({if(dirty)confirmClose=true else close()},Modifier.weight(1f)){Text(tr("Отказ","Cancel"))};Button({save(profile);close()},Modifier.weight(1f)){Text(tr("Запази","Save"))}}}}
 }
 if(confirmClose)AlertDialog({confirmClose=false},title={Text(tr("Незапазени промени","Unsaved changes"))},text={Text(tr("Да затворя ли без запазване?","Close without saving?"))},confirmButton={TextButton({close()}){Text(tr("Затвори","Close"))}},dismissButton={TextButton({confirmClose=false}){Text(tr("Продължи редакцията","Keep editing"))}})
}

@Composable fun CriterionRangeEditor(title:String,selectedMinimum:Double,selectedMaximum:Double,controlMinimum:Double,controlMaximum:Double,step:Double,unit:String,supportingText:String?,errorText:String?,onValueChange:(Double,Double)->Unit,onReset:()->Unit){Column(verticalArrangement=Arrangement.spacedBy(5.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(title,style=MaterialTheme.typography.titleSmall);TextButton(onReset){Text(tr("Нулирай","Reset"))}};Text("${formatNumber(selectedMinimum)}–${formatNumber(selectedMaximum)} $unit");RangeSlider(value=selectedMinimum.toFloat()..selectedMaximum.toFloat(),onValueChange={onValueChange(snapToStep(it.start.toDouble(),controlMinimum,controlMaximum,step),snapToStep(it.endInclusive.toDouble(),controlMinimum,controlMaximum,step))},valueRange=controlMinimum.toFloat()..controlMaximum.toFloat(),steps=calculateSliderSteps(controlMinimum,controlMaximum,step));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){NumberField(tr("Минимум","Minimum"),selectedMinimum,unit,controlMinimum,controlMaximum,Modifier.weight(1f)){onValueChange(it,selectedMaximum)};NumberField(tr("Максимум","Maximum"),selectedMaximum,unit,controlMinimum,controlMaximum,Modifier.weight(1f)){onValueChange(selectedMinimum,it)}};supportingText?.let{Text(it,style=MaterialTheme.typography.bodySmall)};errorText?.let{Text(it,color=MaterialTheme.colorScheme.error)}}}

@Composable fun CriterionSingleValueEditor(title:String,value:Double,controlMinimum:Double,controlMaximum:Double,step:Double,unit:String,onValueChange:(Double)->Unit){Column{Text(title);Slider(value.toFloat(),{onValueChange(snapToStep(it.toDouble(),controlMinimum,controlMaximum,step))},valueRange=controlMinimum.toFloat()..controlMaximum.toFloat(),steps=calculateSliderSteps(controlMinimum,controlMaximum,step));NumberField(title,value,unit,controlMinimum,controlMaximum,Modifier.fillMaxWidth(),onValueChange)}}
@Composable private fun NumberField(label:String,value:Double,unit:String,min:Double,max:Double,modifier:Modifier,onValue:(Double)->Unit){var text by remember(value){mutableStateOf(formatNumber(value))};val parsed=parseLocalizedDecimal(text);OutlinedTextField(text,{text=it;parseLocalizedDecimal(it)?.takeIf{v->v in min..max}?.let(onValue)},modifier,label={Text(label)},suffix={Text(unit)},singleLine=true,isError=parsed==null||parsed !in min..max,keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Decimal))}
@Composable private fun TimeField(label:String,value:LocalTime,modifier:Modifier,onValue:(LocalTime)->Unit){var text by remember(value){mutableStateOf(value.toString())};OutlinedTextField(text,{text=it;runCatching{LocalTime.parse(it)}.getOrNull()?.let(onValue)},modifier,label={Text(label)},singleLine=true)}
private fun formatNumber(v:Double)=if(v%1.0==0.0)"%.0f".format(v) else "%.1f".format(v)
