package bg.blacksea.buoys.ui.activities

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.background
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.horizontalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Close
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import bg.blacksea.buoys.domain.BuoyObservation
import bg.blacksea.buoys.domain.activity.*
import bg.blacksea.buoys.forecast.MarineForecastPoint
import bg.blacksea.buoys.forecast.AtmosphericForecast
import bg.blacksea.buoys.forecast.nearestFuture
import bg.blacksea.buoys.ui.AppLanguage
import bg.blacksea.buoys.ui.activityTitle
import bg.blacksea.buoys.ui.levelTitle
import bg.blacksea.buoys.ui.tr
import java.time.ZoneId
import java.time.format.DateTimeFormatter

@Composable fun ActivitiesScreen(destinationName:String,destinationId:String,observation:BuoyObservation?,forecast:List<MarineForecastPoint>,atmospheric:AtmosphericForecast?,forecastLoading:Boolean,forecastError:String?,refreshForecast:()->Unit,favorites:Set<String>,toggleFavorite:(String)->Unit){
 ActivityWeatherContext.atmospheric=atmospheric
 ActivityCardContext.observation=observation;ActivityCardContext.forecast=forecast
 LaunchedEffect(destinationId){if(forecast.isEmpty())refreshForecast()}
 val engine=remember{DefaultActivityEvaluationEngine()};var details by remember{mutableStateOf<MarineActivityType?>(null)};val ratings=remember(observation,forecast){MarineActivityType.entries.associateWith{engine.evaluate(it,observation,forecast)}};val ordered=MarineActivityType.entries.sortedWith(compareByDescending<MarineActivityType>{it.name in favorites}.thenBy{it.title})
 Column(Modifier.fillMaxSize().padding(12.dp)){Text(tr("Морски спортове","Marine sports"),fontSize=25.sp,fontWeight=FontWeight.Bold);Text(destinationName,style=MaterialTheme.typography.titleMedium);Spacer(Modifier.height(10.dp));LazyVerticalGrid(GridCells.Fixed(2),horizontalArrangement=Arrangement.spacedBy(10.dp),verticalArrangement=Arrangement.spacedBy(10.dp),modifier=Modifier.weight(1f)){if(favorites.isNotEmpty())item(span={GridItemSpan(2)}){Text(tr("Любими спортове","Favorite sports"),fontWeight=FontWeight.Bold,modifier=Modifier.padding(vertical=6.dp))};items(ordered.filter{it.name in favorites}){activity->ActivityCard(activity,ratings.getValue(activity),true,{toggleFavorite(activity.name)}){details=activity}};item(span={GridItemSpan(2)}){Text(tr("Всички спортове","All sports"),fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=10.dp,bottom=6.dp))};items(ordered.filterNot{it.name in favorites}){activity->ActivityCard(activity,ratings.getValue(activity),false,{toggleFavorite(activity.name)}){details=activity}}};Text(tr("Оценката е ориентировъчна. Проверявайте местните условия, предупрежденията на властите и собствената си подготовка.","The rating is indicative. Check local conditions, official warnings and your own preparation."),style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=8.dp))}
 details?.let{activity->ActivityDetails(activity,destinationId,ratings.getValue(activity),forecast,forecastLoading,forecastError,refreshForecast,engine,activity.name in favorites,{toggleFavorite(activity.name)}){details=null}}
}
@Composable private fun ActivityCard(activity:MarineActivityType,rating:ActivitySuitability,favorite:Boolean,toggle:()->Unit,open:()->Unit){val color=levelColor(rating.level);Card(onClick=open,colors=CardDefaults.cardColors(containerColor=color.copy(alpha=.14f)),modifier=Modifier.fillMaxWidth().heightIn(min=190.dp)){Column(Modifier.fillMaxWidth().padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Text(activity.icon,fontSize=22.sp,modifier=Modifier.width(32.dp));Text(activityTitle(activity),fontWeight=FontWeight.Bold,fontSize=if(activity.title.length>16)16.sp else 18.sp,maxLines=2,overflow=TextOverflow.Ellipsis,softWrap=true,modifier=Modifier.weight(1f));IconButton(onClick=toggle,modifier=Modifier.size(48.dp)){Text(if(favorite)"★" else "☆",fontSize=25.sp,color=MaterialTheme.colorScheme.primary)}};Text(levelTitle(rating.level),color=color,fontWeight=FontWeight.SemiBold,maxLines=2);Text(compactActivityMetrics(activity),maxLines=2,overflow=TextOverflow.Ellipsis,style=MaterialTheme.typography.bodySmall)}}}
@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun ActivityDetails(activity:MarineActivityType,destinationId:String,rating:ActivitySuitability,forecast:List<MarineForecastPoint>,forecastLoading:Boolean,forecastError:String?,refreshForecast:()->Unit,engine:ActivityEvaluationEngine,favorite:Boolean,toggle:()->Unit,close:()->Unit){LaunchedEffect(forecast.isEmpty()){if(forecast.isEmpty()&&!forecastLoading)refreshForecast()};var editing by remember{mutableStateOf(false)};if(editing)ActivityCriteriaEditor(activity,ActivityCriteriaContext.profiles[activity],ActivityCriteriaContext.save,{ActivityCriteriaContext.reset(activity)}){editing=false}else ActivityDetailsMenu(activity,destinationId,rating,forecast,engine,favorite,toggle,{editing=true},close)}
@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun ActivityDetailsMenu(activity:MarineActivityType,destinationId:String,rating:ActivitySuitability,forecast:List<MarineForecastPoint>,engine:ActivityEvaluationEngine,favorite:Boolean,toggle:()->Unit,editCriteria:()->Unit,close:()->Unit){
 var range by remember{mutableIntStateOf(1)};var selectedDate by remember{mutableStateOf<java.time.LocalDate?>(null)}
 val daily=remember(activity,forecast,ActivityCriteriaContext.profiles[activity]){dailyActivityForecasts(activity,destinationId,forecast,engine)};val visible=daily.take(if(range==1)1 else range);val selected=selectedDate?.let{date->visible.firstOrNull{it.date==date}}?:visible.firstOrNull()
 ModalBottomSheet(onDismissRequest=close){Column(Modifier.fillMaxWidth().navigationBarsPadding().verticalScroll(rememberScrollState()).padding(start=20.dp,end=20.dp,top=20.dp,bottom=48.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  Row(verticalAlignment=Alignment.CenterVertically){Text("${activity.icon} ${activityTitle(activity)}",fontSize=24.sp,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));TextButton(onClick=toggle){Text(if(favorite)tr("★ В любими","★ Favorite")else tr("☆ Добави","☆ Add"))};IconButton(onClick=close){Icon(Icons.Default.Close,tr("Затвори","Close"))}}
  Button(onClick=editCriteria,modifier=Modifier.fillMaxWidth()){Text(tr("Настрой критериите","Adjust criteria"))}
  Text(tr("Променете границите, нивото на опит и часовете за оценка за този спорт.","Change limits, experience level and evaluation hours for this sport."),style=MaterialTheme.typography.bodySmall)
  SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){listOf(1 to tr("24 часа","24 hours"),3 to tr("3 дни","3 days"),7 to tr("7 дни","7 days")).forEachIndexed{i,(value,label)->SegmentedButton(range==value,{range=value;selectedDate=null},SegmentedButtonDefaults.itemShape(i,3)){Text(label)}}}
  if(range>1)visible.forEach{day->DailyWideCard(day,selected?.date==day.date){selectedDate=day.date}}else visible.firstOrNull()?.let{DailyCard(it,true){}}
  Text("${tr("Оценка","Score")}: ${selected?.score?:rating.score}/100",fontWeight=FontWeight.Bold,color=levelColor(selected?.level?:rating.level));Text(selected?.summary?:rating.summary)
  selected?.let{day->Text(tr("Почасова прогноза","Hourly forecast"),fontWeight=FontWeight.Bold);Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){day.hourlyEvaluations.forEach{HourlyActivityCard(it)}}}
  Text(tr("Източник: прогноза Open-Meteo Marine","Source: Open-Meteo Marine forecast"),style=MaterialTheme.typography.bodySmall);HorizontalDivider();Text(tr("Оценката не гарантира безопасност. Проверете местните условия и официалните предупреждения.","The rating does not guarantee safety. Check local conditions and official warnings."),style=MaterialTheme.typography.bodySmall);Spacer(Modifier.height(20.dp))
 }}
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun ActivityDetails(activity:MarineActivityType,destinationId:String,rating:ActivitySuitability,forecast:List<MarineForecastPoint>,engine:ActivityEvaluationEngine,favorite:Boolean,toggle:()->Unit,close:()->Unit){var range by remember{mutableIntStateOf(1)};val daily=remember(activity,forecast){dailyActivityForecasts(activity,destinationId,forecast,engine)};var selectedDate by remember{mutableStateOf<java.time.LocalDate?>(null)};val visible=daily.take(if(range==1)1 else range);val selected=selectedDate?.let{d->visible.firstOrNull{it.date==d}}?:visible.firstOrNull();val windows=selected?.bestTimeWindows?:suitableWindows(activity,forecast.take(24),engine);ModalBottomSheet(onDismissRequest=close){Column(Modifier.fillMaxWidth().verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("${activity.icon} ${activity.title}",fontSize=24.sp,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));TextButton(onClick=toggle){Text(if(favorite)"★ В любими" else "☆ Добави")};IconButton(onClick=close){Icon(Icons.Default.Close,"Затвори")}};SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){listOf(1 to "24 часа",3 to "3 дни",7 to "7 дни").forEachIndexed{i,(value,label)->SegmentedButton(range==value,{range=value;selectedDate=null},SegmentedButtonDefaults.itemShape(i,3)){Text(label)}}};Text(when(range){1->"Прогноза за следващите 24 часа";3->"Прогноза за 3 дни";else->"Прогноза за 7 дни"},fontWeight=FontWeight.Bold);if(range>1){visible.forEach{day->DailyWideCard(day,selected?.date==day.date){selectedDate=day.date}}}else visible.firstOrNull()?.let{day->DailyCard(day,true){}};val shown=selected;Text("Подробности за ${shown?.date?.format(java.time.format.DateTimeFormatter.ofPattern("dd.MM"))?:"избрания период"}",fontWeight=FontWeight.Bold);Text(shown?.title?:rating.title,color=levelColor(shown?.level?:rating.level),fontSize=20.sp,fontWeight=FontWeight.Bold);Text("Оценка: ${shown?.score?:rating.score}/100");Text(shown?.summary?:rating.summary);Text("Източник: прогноза Open-Meteo Marine")
 Text("Подходящи часове",fontWeight=FontWeight.Bold);if(windows.isEmpty())Text("Не е намерен надежден подходящ прозорец.")else windows.take(4).forEach{w->val f=DateTimeFormatter.ofPattern("dd.MM HH:mm").withZone(ZoneId.of("Europe/Sofia"));Text("${f.format(w.start)}–${DateTimeFormatter.ofPattern("HH:mm").withZone(ZoneId.of("Europe/Sofia")).format(w.end)} · ${w.level.title}")};shown?.let{day->Text("Почасова прогноза",fontWeight=FontWeight.Bold);Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){day.hourlyEvaluations.forEach{h->HourlyActivityCard(h)}}};if(rating.reasons.isNotEmpty()){Text("Положителни фактори",fontWeight=FontWeight.Bold);rating.reasons.forEach{Text("✓ $it")}};val allWarnings=(shown?.warnings.orEmpty()+rating.warnings).distinct();if(allWarnings.isNotEmpty()){Text("Предупреждения",fontWeight=FontWeight.Bold);allWarnings.forEach{Text("⚠ $it",color=MaterialTheme.colorScheme.error)}};HorizontalDivider();Text("Оценката не означава, че активността е безопасна. Проверете локалните условия.",style=MaterialTheme.typography.bodySmall);Spacer(Modifier.height(24.dp))}}}
@Composable private fun DailyCard(day:ActivityDailyForecast,selected:Boolean,open:()->Unit){val color=levelColor(day.level);Card(onClick=open,colors=CardDefaults.cardColors(containerColor=color.copy(alpha=if(selected).30f else .16f)),modifier=Modifier.width(190.dp)){Column{Box(Modifier.fillMaxWidth().height(6.dp).background(color));Column(Modifier.padding(10.dp),verticalArrangement=Arrangement.spacedBy(3.dp)){Text(day.date.format(java.time.format.DateTimeFormatter.ofPattern("EEE dd.MM")),fontWeight=FontWeight.Bold);DailyValues(day);Text("${tr("Оценка","Score")}: ${day.score}/100",color=color,fontWeight=FontWeight.SemiBold)}}}}
@Composable private fun DailyWideCard(day:ActivityDailyForecast,selected:Boolean,open:()->Unit){val color=levelColor(day.level);Card(onClick=open,colors=CardDefaults.cardColors(containerColor=color.copy(alpha=if(selected).30f else .15f)),modifier=Modifier.fillMaxWidth()){Row{Box(Modifier.width(7.dp).height(142.dp).background(color));Column(Modifier.weight(1f).padding(12.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text(day.date.format(java.time.format.DateTimeFormatter.ofPattern("EEEE, dd.MM")),fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));Text("${day.score}/100",color=color,fontWeight=FontWeight.Bold)};DailyValues(day)}}}}
@Composable private fun DailyValues(day:ActivityDailyForecast){val daytime=day.activityType==MarineActivityType.BEACH||day.activityType==MarineActivityType.SWIMMING;val hours=if(daytime)day.hourlyEvaluations.filter{it.forecastAt.atZone(ZoneId.of("Europe/Sofia")).hour in 9..19}else day.hourlyEvaluations;val wave=hours.mapNotNull{it.waveHeightM}.maxOrNull();val interval=hours.mapNotNull{it.wavePeriodS}.maxOrNull();val wind=hours.mapNotNull{it.windSpeedMs}.maxOrNull();val airMin=hours.mapNotNull{it.airTemperatureC}.minOrNull();val airMax=hours.mapNotNull{it.airTemperatureC}.maxOrNull();val sea=hours.mapNotNull{it.waterTemperatureC}.average().takeUnless{it.isNaN()};Text("${tr("Вълни до","Waves up to")}: ${wave?.let{"%.1f m".format(it)}?:"—"}  •  ${tr("Интервал","Interval")}: ${interval?.let{"%.1f s".format(it)}?:"—"}",style=MaterialTheme.typography.bodySmall);Text("${tr("Вятър до","Wind up to")}: ${wind?.let{"%.1f m/s".format(it)}?:"—"}",style=MaterialTheme.typography.bodySmall);Text("${if(daytime)tr("Въздух денем","Daytime air")else tr("Въздух","Air")}: ${airMin?.let{"%.0f".format(it)}?:"—"}–${airMax?.let{"%.0f °C".format(it)}?:"—"}  •  ${tr("Море","Sea")}: ${sea?.let{"%.1f °C".format(it)}?:"—"}",style=MaterialTheme.typography.bodySmall)}
@Composable private fun HourlyActivityCard(h:ActivityHourlyEvaluation){val local=h.forecastAt.atZone(ZoneId.of("Europe/Sofia"));val day=local.hour in 7..19;val background=if(day)Color(0xFFFFF1CC)else Color(0xFF24324A);val content=if(day)Color(0xFF292316)else Color(0xFFF2F5FA);Card(colors=CardDefaults.cardColors(containerColor=background,contentColor=content),modifier=Modifier.width(142.dp)){Column(Modifier.padding(9.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(local.format(DateTimeFormatter.ofPattern("HH:mm")),fontWeight=FontWeight.Bold);Text(if(day)"☀" else "☾")};Text("${h.score}/100",color=if(day)levelColor(h.level)else Color(0xFFFFD166),fontWeight=FontWeight.Bold);Text(h.airTemperatureC?.let{"${tr("Въздух","Air")} %.1f °C".format(it)}?:"${tr("Въздух","Air")} —");Text(h.waterTemperatureC?.let{"${tr("Море","Sea")} %.1f °C".format(it)}?:"${tr("Море","Sea")} —");Text(h.waveHeightM?.let{"${tr("Вълни","Waves")} %.1f m".format(it)}?:tr("Няма вълни","No wave data"));Text(h.wavePeriodS?.let{"${tr("Интервал","Interval")} %.1f s".format(it)}?:tr("Няма интервал","No interval"),style=MaterialTheme.typography.bodySmall)}}}
private object ActivityCardContext{var observation:BuoyObservation?=null;var forecast:List<MarineForecastPoint> = emptyList()}
private fun compactActivityMetrics(activity:MarineActivityType):String{
 val marine=ActivityCardContext.forecast.nearestFuture()?:ActivityCardContext.forecast.firstOrNull()
 val observation=ActivityCardContext.observation
 val weather=ActivityWeatherContext.atmospheric?.hourly?.minByOrNull{kotlin.math.abs(it.time.epochSecond-java.time.Instant.now().epochSecond)}
 val wave=(marine?.waveHeightM?:observation?.significantWaveHeightM)?.let{"%.1f m".format(it)}?:"—"
 val wind=(weather?.windSpeedMetersPerSecond?:observation?.windSpeedMs)?.let{"%.1f m/s".format(it)}?:"—"
 val gust=weather?.windGustMetersPerSecond?.let{"%.1f m/s".format(it)}?:"—"
 val sea=(marine?.seaSurfaceTemperatureC?:observation?.waterTemperatureC)?.let{"%.0f °C".format(it)}?:"—"
 val air=weather?.airTemperatureCelsius?.let{"%.0f °C".format(it)}?:"—"
 val period=(marine?.wavePeriodS?:observation?.wavePeriodS)?.let{"%.1f s".format(it)}?:"—"
 return when(activity){MarineActivityType.SWIMMING->"${tr("Море","Sea")} $sea · ${tr("Вълни","Waves")} $wave";MarineActivityType.SURFING->"${tr("Вълни","Waves")} $wave · ${tr("Интервал","Interval")} $period";MarineActivityType.WINDSURFING,MarineActivityType.KITESURFING->"${tr("Вятър","Wind")} $wind · ${tr("Пориви","Gusts")} $gust";MarineActivityType.DIVING,MarineActivityType.SPEARFISHING->"${tr("Вълни","Waves")} $wave · ${tr("Море","Sea")} $sea";MarineActivityType.BEACH->"${tr("Въздух","Air")} $air · UV ${weather?.uvIndex?.let{"%.0f".format(it)}?:"—"}";MarineActivityType.SAILING->"${tr("Вятър","Wind")} $wind · ${tr("Вълни","Waves")} $wave";MarineActivityType.SMALL_BOAT->"${tr("Вълни","Waves")} $wave · ${tr("Пориви","Gusts")} $gust";else->"${tr("Вълни","Waves")} $wave · ${tr("Вятър","Wind")} $wind"}
}
private fun levelColor(level:ActivitySuitabilityLevel)=when(level){ActivitySuitabilityLevel.EXCELLENT->Color(0xFF087F5B);ActivitySuitabilityLevel.GOOD->Color(0xFF2B8A3E);ActivitySuitabilityLevel.ACCEPTABLE->Color(0xFFE67700);ActivitySuitabilityLevel.POOR->Color(0xFF607D8B);ActivitySuitabilityLevel.DANGEROUS->Color(0xFFC92A2A);ActivitySuitabilityLevel.NO_DATA->Color.Gray}

@Composable fun ActivitiesScreen(destinationName:String,destinationId:String,observation:BuoyObservation?,forecast:List<MarineForecastPoint>,favorites:Set<String>,toggleFavorite:(String)->Unit)=ActivitiesScreen(destinationName,destinationId,observation,forecast,null,false,null,{},favorites,toggleFavorite)
@Composable fun ActivitiesScreen(destinationName:String,destinationId:String,observation:BuoyObservation?,forecast:List<MarineForecastPoint>,atmospheric:AtmosphericForecast?,favorites:Set<String>,toggleFavorite:(String)->Unit)=ActivitiesScreen(destinationName,destinationId,observation,forecast,atmospheric,false,null,{},favorites,toggleFavorite)
