package bg.blacksea.buoys.domain.activity

import bg.blacksea.buoys.forecast.MarineForecastPoint
import bg.blacksea.buoys.forecast.AtmosphericForecast
import java.time.ZoneId

object ActivityWeatherContext{var atmospheric:AtmosphericForecast?=null}
fun dailyActivityForecasts(activity:MarineActivityType,destinationId:String,forecast:List<MarineForecastPoint>,engine:ActivityEvaluationEngine,preferences:ActivityPreferences=ActivityPreferences(),atmospheric:AtmosphericForecast?=ActivityWeatherContext.atmospheric):List<ActivityDailyForecast>{
 val zone=ZoneId.of("Europe/Sofia");return forecast.groupBy{it.forecastAt.atZone(zone).toLocalDate()}.toSortedMap().map{(date,points)->
  val profile=ActivityProfileFactory.default(activity);val weatherDay=atmospheric?.daily?.firstOrNull{it.date==date};val sorted=points.sortedBy{it.forecastAt};val evaluations=sorted.map{p->val r=engine.evaluate(activity,null,listOf(p),preferences);val weatherHour=atmospheric?.hourly?.minByOrNull{kotlin.math.abs(it.time.epochSecond-p.forecastAt.epochSecond)}?.takeIf{kotlin.math.abs(it.time.epochSecond-p.forecastAt.epochSecond)<=5400};val air=weatherHour?.airTemperatureCelsius;val comfortAir=weatherHour?.apparentTemperatureCelsius?:air;val adjusted=activityProfileScore(profile,comfortAir,p.seaSurfaceTemperatureC,p.waveHeightM,p.wavePeriodS,p.swellWaveHeightM,p.swellWavePeriodS,weatherHour?.windSpeedMetersPerSecond,weatherHour?.windGustMetersPerSecond,weatherHour?.precipitationMillimeters,weatherHour?.thunderstormProbabilityPercent);val adjustedLevel=scoreLevel(adjusted);ActivityHourlyEvaluation(p.forecastAt,adjusted,adjustedLevel,p.waveHeightM,p.wavePeriodS,p.waveDirectionDeg,weatherHour?.windSpeedMetersPerSecond,weatherHour?.windGustMetersPerSecond,null,p.seaSurfaceTemperatureC,air,weatherHour?.precipitationMillimeters,r.warnings)}
  val relevant=evaluations.filter{profile.timePolicy.includes(it.forecastAt,date,weatherDay,zone)};val windows=windowsFromEvaluations(relevant,profile.minimumWindowHours);val best=windows.maxByOrNull{it.averageScore};val dangerous=relevant.isNotEmpty()&&relevant.count{it.level==ActivitySuitabilityLevel.DANGEROUS}>=maxOf(2,relevant.size/2);val usableHours=best?.let{((it.end.epochSecond-it.start.epochSecond)/3600).toInt()}?:0
  var score=relevant.map{it.score}.sortedDescending().take(5).average().takeUnless{it.isNaN()}?.toInt()?:0;if(usableHours==1)score-=15;if(dangerous)score=minOf(score,49);score=score.coerceIn(0,100)
  val level=when{evaluations.isEmpty()->ActivitySuitabilityLevel.NO_DATA;dangerous&&best==null->ActivitySuitabilityLevel.DANGEROUS;score>=90->ActivitySuitabilityLevel.EXCELLENT;score>=70->ActivitySuitabilityLevel.GOOD;score>=50->ActivitySuitabilityLevel.ACCEPTABLE;score>=25->ActivitySuitabilityLevel.POOR;else->ActivitySuitabilityLevel.DANGEROUS}
  val warnings=evaluations.flatMap{it.warnings}.distinct();ActivityDailyForecast(activity,destinationId,date,score,level,level.title,if(best==null)"Не е намерен подходящ часови прозорец" else "Най-добър прозорец: $usableHours часа",windows.sortedByDescending{it.averageScore}.take(3),evaluations,emptyList(),warnings,SuitabilitySourceType.FORECAST)
 }}

private fun scoreLevel(score:Int)=when{score>=90->ActivitySuitabilityLevel.EXCELLENT;score>=70->ActivitySuitabilityLevel.GOOD;score>=50->ActivitySuitabilityLevel.ACCEPTABLE;score>=25->ActivitySuitabilityLevel.POOR;else->ActivitySuitabilityLevel.DANGEROUS}
private fun windowsFromEvaluations(values:List<ActivityHourlyEvaluation>,minimumHours:Int):List<ActivityTimeWindow>{val usable=values.filter{it.score>=50}.sortedBy{it.forecastAt};if(usable.isEmpty())return emptyList();val groups=mutableListOf<MutableList<ActivityHourlyEvaluation>>();usable.forEach{item->val last=groups.lastOrNull();if(last!=null&&item.forecastAt.epochSecond-last.last().forecastAt.epochSecond<=3700)last+=item else groups+=mutableListOf(item)};return groups.filter{it.size>=minimumHours}.map{g->val scores=g.map{it.score};ActivityTimeWindow(g.first().forecastAt,g.last().forecastAt.plusSeconds(3600),scores.min(),scores.average().toInt(),g.minBy{it.score}.level,g.flatMap{it.warnings}.distinct())}}
internal fun activityProfileScore(profile:ActivityEvaluationProfile,air:Double?,sea:Double?,wave:Double?,period:Double?,swell:Double?,swellPeriod:Double?,wind:Double?,gust:Double?,precipitation:Double?,thunder:Double?,officialWarning:Boolean=false):Int{val values=mapOf(MarineParameter.APPARENT_TEMPERATURE to air,MarineParameter.AIR_TEMPERATURE to air,MarineParameter.SEA_TEMPERATURE to sea,MarineParameter.WAVE_HEIGHT to wave,MarineParameter.WAVE_PERIOD to period,MarineParameter.SWELL_HEIGHT to swell,MarineParameter.SWELL_PERIOD to swellPeriod,MarineParameter.WIND_SPEED to wind,MarineParameter.WIND_GUST to gust,MarineParameter.PRECIPITATION to precipitation,MarineParameter.THUNDERSTORM_PROBABILITY to thunder);if(profile.requiredParameters.count{values[it]!=null}<profile.minimumRequiredParameterCount)return 40;return evaluateActivityConditions(profile,values,officialWarning).score}
internal fun activitySpecificScore(activity:MarineActivityType,base:Int,air:Double?,sea:Double?,wave:Double?,swell:Double?):Int{var score=base;when(activity){
 MarineActivityType.BEACH->{score=when{air==null->45;air<20->15;air<22->25;air<24->40;air<26->60;air<=31->90;air<=34->70;else->40};if(sea==null)score-=15 else score-=when{sea<16->40;sea<19->25;sea<22->10;else->0};score-=when{(wave?:0.0)>.8->25;(wave?:0.0)>.5->10;else->0}}
 MarineActivityType.SWIMMING->{if(sea==null)score=minOf(score,45)else score-=when{sea<16->50;sea<19->30;sea<22->15;else->0};if((wave?:0.0)>.4)score-=35}
 MarineActivityType.DIVING,MarineActivityType.SPEARFISHING->{if(sea==null)score=minOf(score,50)else if(sea<16)score-=25;if((wave?:0.0)>.5)score-=35}
 MarineActivityType.SUP,MarineActivityType.KAYAK,MarineActivityType.SMALL_BOAT->{if((wave?:0.0)>.6)score-=30}
 MarineActivityType.SURFING->{if(swell==null)score=minOf(score,55)else if(swell<.3)score-=30}
 MarineActivityType.KITESURFING,MarineActivityType.WINDSURFING,MarineActivityType.SAILING->{score=minOf(score,55)}
 else->Unit};return score.coerceIn(0,100)}
