package bg.blacksea.buoys.domain.activity

enum class ActivitySafetyLevel{NORMAL,CAUTION,DANGEROUS,UNKNOWN}
enum class SportSuitability{GOOD,ACCEPTABLE,POOR,UNAVAILABLE}
enum class CriterionResult{BELOW_USEFUL,OPTIMAL,ABOVE_PREFERRED,CAUTION,DANGEROUS,NO_DATA}
data class ActivityParameterThreshold(val minimumUseful:Double?,val optimalMinimum:Double?,val optimalMaximum:Double?,val cautionMaximum:Double?,val dangerousMaximum:Double?,val unit:String)
data class ActivityCriterionResult(val parameter:MarineParameter,val actualValue:Double?,val threshold:ActivityParameterThreshold,val result:CriterionResult,val suitabilityReason:Boolean,val safetyReason:Boolean,val blocking:Boolean)
data class ActivityConditionEvaluation(val score:Int,val suitability:SportSuitability,val safetyLevel:ActivitySafetyLevel,val primaryMessage:String,val secondaryMessage:String?=null,val criteria:List<ActivityCriterionResult> = emptyList())

private fun safetyMaximums(activity:MarineActivityType,parameter:MarineParameter):Pair<Double?,Double?> = when(parameter){
 MarineParameter.WIND_SPEED->when(activity){MarineActivityType.SUP->8.0 to 12.0;MarineActivityType.KAYAK->9.0 to 13.0;MarineActivityType.SAILING->14.0 to 17.0;MarineActivityType.WINDSURFING->14.0 to 18.0;MarineActivityType.KITESURFING->14.0 to 17.0;MarineActivityType.SMALL_BOAT->10.0 to 14.0;else->12.0 to 16.0}
 MarineParameter.WIND_GUST->when(activity){MarineActivityType.SUP->11.0 to 15.0;MarineActivityType.KITESURFING->17.0 to 21.0;MarineActivityType.SAILING,MarineActivityType.WINDSURFING->18.0 to 22.0;else->14.0 to 18.0}
 MarineParameter.WAVE_HEIGHT->when(activity){MarineActivityType.SWIMMING->.7 to 1.2;MarineActivityType.SUP->.7 to 1.2;MarineActivityType.KAYAK->1.0 to 1.5;MarineActivityType.DIVING,MarineActivityType.SPEARFISHING->.8 to 1.3;MarineActivityType.SMALL_BOAT->1.5 to 2.2;MarineActivityType.SURFING->2.5 to 3.5;else->2.0 to 3.0}
 MarineParameter.SWELL_HEIGHT->2.0 to 3.0
 MarineParameter.THUNDERSTORM_PROBABILITY->30.0 to 60.0
 else->null to null
}

internal fun evaluateActivityConditions(profile:ActivityEvaluationProfile,values:Map<MarineParameter,Double?>,officialWarning:Boolean=false):ActivityConditionEvaluation{
 if(officialWarning)return ActivityConditionEvaluation(0,SportSuitability.POOR,ActivitySafetyLevel.DANGEROUS,"Официално предупреждение")
 var score=90;var safety=ActivitySafetyLevel.NORMAL;val results=mutableListOf<ActivityCriterionResult>();val suitabilityReasons=mutableListOf<String>();val safetyReasons=mutableListOf<String>()
 profile.requiredParameters.forEach{if(values[it]==null)return@forEach}
 ActivityCriterionDefinitions.forActivity(profile.activityType).forEach{d->val actual=values[d.parameter];val preferred=profile.thresholds.range(d.parameter)?:return@forEach;val (caution,danger)=safetyMaximums(profile.activityType,d.parameter);val threshold=ActivityParameterThreshold(preferred.minimum,preferred.minimum,preferred.maximum,caution,danger,d.unit);val result=when{actual==null->CriterionResult.NO_DATA;danger!=null&&actual>danger->CriterionResult.DANGEROUS;caution!=null&&actual>caution->CriterionResult.CAUTION;preferred.minimum!=null&&actual<preferred.minimum->CriterionResult.BELOW_USEFUL;preferred.maximum!=null&&actual>preferred.maximum->CriterionResult.ABOVE_PREFERRED;else->CriterionResult.OPTIMAL};when(result){CriterionResult.BELOW_USEFUL->{score=minOf(score,40);suitabilityReasons+=lowMessage(profile.activityType,d.parameter)};CriterionResult.ABOVE_PREFERRED->{score=minOf(score,55);suitabilityReasons+="Извън предпочитания диапазон"};CriterionResult.CAUTION->{score=minOf(score,40);safety=ActivitySafetyLevel.CAUTION;safetyReasons+="Условия с повишено внимание"};CriterionResult.DANGEROUS->{score=0;safety=ActivitySafetyLevel.DANGEROUS;safetyReasons+=dangerMessage(d.parameter)};else->{}};results+=ActivityCriterionResult(d.parameter,actual,threshold,result,result==CriterionResult.BELOW_USEFUL||result==CriterionResult.ABOVE_PREFERRED,result==CriterionResult.CAUTION||result==CriterionResult.DANGEROUS,result==CriterionResult.DANGEROUS)}
 val wind=values[MarineParameter.WIND_SPEED];val gust=values[MarineParameter.WIND_GUST];if(profile.activityType in setOf(MarineActivityType.SUP,MarineActivityType.KITESURFING)&&wind!=null&&gust!=null&&gust-wind>5&&safety!=ActivitySafetyLevel.DANGEROUS){safety=ActivitySafetyLevel.CAUTION;score=minOf(score,65);safetyReasons+="Поривист вятър"}
 val suitability=when{values.values.all{it==null}->SportSuitability.UNAVAILABLE;score>=70->SportSuitability.GOOD;score>=50->SportSuitability.ACCEPTABLE;else->SportSuitability.POOR};val specific=when(profile.activityType){MarineActivityType.SAILING->suitabilityReasons.firstOrNull{it.contains("Слаб вятър")};MarineActivityType.KITESURFING->suitabilityReasons.firstOrNull{it.contains("Недостатъчен вятър")};MarineActivityType.SURFING->suitabilityReasons.firstOrNull{it.contains("Малки вълни")};else->null};val primary=when{safety==ActivitySafetyLevel.DANGEROUS->safetyReasons.firstOrNull()?:"Опасни условия";specific!=null->specific;safety==ActivitySafetyLevel.CAUTION&&suitability!=SportSuitability.POOR->"Подходящо с повишено внимание";suitabilityReasons.isNotEmpty()->suitabilityReasons.first();suitability==SportSuitability.GOOD->"Добри условия";suitability==SportSuitability.ACCEPTABLE->"Приемливи условия";else->"Недостатъчно данни"};return ActivityConditionEvaluation(score,suitability,safety,primary,safetyReasons.firstOrNull(),results)
}

private fun lowMessage(a:MarineActivityType,p:MarineParameter)=when{a==MarineActivityType.SURFING&&p in setOf(MarineParameter.WAVE_HEIGHT,MarineParameter.WAVE_PERIOD,MarineParameter.SWELL_HEIGHT)->"Малки вълни за сърф";a==MarineActivityType.KITESURFING&&p==MarineParameter.WIND_SPEED->"Недостатъчен вятър за кайтсърф";a==MarineActivityType.SAILING&&p==MarineParameter.WIND_SPEED->"Слаб вятър за ветроходство";p==MarineParameter.AIR_TEMPERATURE||p==MarineParameter.SEA_TEMPERATURE->"Температурата е извън предпочитания диапазон";else->"Недостатъчни условия за спорта"}
private fun dangerMessage(p:MarineParameter)=when(p){MarineParameter.WIND_SPEED,MarineParameter.WIND_GUST->"Опасно силен вятър";MarineParameter.WAVE_HEIGHT,MarineParameter.SWELL_HEIGHT->"Опасно високи вълни";MarineParameter.THUNDERSTORM_PROBABILITY->"Опасност от гръмотевици";else->"Опасни условия"}
