package bg.blacksea.buoys.domain.activity

import bg.blacksea.buoys.domain.*
import bg.blacksea.buoys.forecast.MarineForecastPoint
import java.time.*

interface ActivityEvaluationEngine{fun evaluate(activity:MarineActivityType,observation:BuoyObservation?,forecast:List<MarineForecastPoint>,preferences:ActivityPreferences=ActivityPreferences()):ActivitySuitability}
class DefaultActivityEvaluationEngine:ActivityEvaluationEngine{
 override fun evaluate(activity:MarineActivityType,observation:BuoyObservation?,forecast:List<MarineForecastPoint>,preferences:ActivityPreferences):ActivitySuitability{
  val future=forecast.filter{!it.forecastAt.isBefore(Instant.now())}.minByOrNull{it.forecastAt};val customLegacyLimits=preferences!=ActivityPreferences();val wave=if(customLegacyLimits)observation?.significantWaveHeightM?:future?.waveHeightM else future?.waveHeightM?:observation?.significantWaveHeightM;val weather=ActivityWeatherContext.atmospheric?.hourly?.minByOrNull{h->kotlin.math.abs(h.time.epochSecond-(future?.forecastAt?:Instant.now()).epochSecond)};val wind=weather?.windSpeedMetersPerSecond?:observation?.windSpeedMs;val temp=future?.seaSurfaceTemperatureC?:observation?.waterTemperatureC;val period=future?.wavePeriodS?:observation?.wavePeriodS;val cached=observation?.isCached==true
  if(wave==null||temp==null)return result(activity,0,ActivitySuitabilityLevel.NO_DATA,"Липсват критични данни",emptyList(),listOf("Не може да се направи надеждна оценка"),source(observation,future,cached))
  var score=82;val reasons=mutableListOf<String>();val warnings=mutableListOf<String>();fun penalty(value:Int,text:String){score-=value;warnings+=text};fun good(text:String){reasons+=text}
  when(activity){
   MarineActivityType.FISHING->{if(wave<=.7)good("Умерени вълни")else penalty(35,"Високи вълни");if(wind!=null&&wind>10)penalty(25,"Силен вятър")}
   MarineActivityType.KITESURFING->{if(wind==null)penalty(30,"Няма измерена скорост на вятъра")else if(wind<preferences.minimumWindMs)penalty(35,"Вятърът е прекалено слаб")else if(wind>preferences.maximumWindMs)penalty(55,"Вятърът превишава зададения максимум")else good("Вятърът е в зададените граници");if(wave>preferences.maximumWaveM)penalty(35,"Вълните са високи за профила")}
   MarineActivityType.WINDSURFING->{if(wind==null)penalty(30,"Няма измерен вятър")else if(wind in 5.0..12.0)good("Подходящ вятър")else penalty(30,"Вятърът е извън предпочитаните граници");if(wave>1.5)penalty(35,"Високи вълни")}
   MarineActivityType.SURFING->{val swell=future?.swellWaveHeightM;if((swell?:wave)<.3)penalty(30,"Недостатъчно вълнение")else good("Има вълнение");if(wave>2.0)penalty(50,"Много високи вълни")}
   MarineActivityType.DIVING,MarineActivityType.SPEARFISHING->{if(wave>.5)penalty(45,"Вълните затрудняват влизането")else good("Ниски вълни");if(temp<16)penalty(20,"Студена вода");warnings+="Няма надеждни данни за видимост и течения"}
   MarineActivityType.SUP,MarineActivityType.KAYAK->{if(wave>.5)penalty(50,"Вълните са високи")else good("Спокойна водна повърхност");if(wind!=null&&wind>7)penalty(40,"Силен вятър за тази активност")}
   MarineActivityType.SMALL_BOAT->{if(wave>preferences.maximumWaveM)penalty(60,"Вълната превишава зададения максимум")else good("Вълните са в зададените граници");if(wind!=null&&wind>preferences.maximumWindMs)penalty(50,"Вятърът превишава зададения максимум")}
   MarineActivityType.SAILING->{if(wind==null)penalty(35,"Няма измерен вятър")else if(wind in preferences.minimumWindMs..preferences.maximumWindMs)good("Желан диапазон на вятъра")else penalty(35,"Вятърът е извън зададения диапазон");if(wave>preferences.maximumWaveM)penalty(45,"Високи вълни")}
   MarineActivityType.SWIMMING->{if(wave>.4)penalty(60,"Високи вълни за плуване")else good("Ниски вълни");if(temp<18)penalty(30,"Студена вода");warnings+="Няма данни за флагове, течения и локални забрани"}
   MarineActivityType.BEACH->{if(temp<18)penalty(25,"Хладна морска вода")else good("Приятна температура на морето");if(wind!=null&&wind>10)penalty(25,"Силен вятър")}
  }
  if(cached)penalty(25,"Данните са кеширани");if(observation!=null&&freshness(observation.measuredAtUtc)==Freshness.VERY_OLD)return result(activity,20,ActivitySuitabilityLevel.NO_DATA,"Измерването е много старо",reasons,warnings+"Остарели измервания",SuitabilitySourceType.CACHED)
  val profile=ActivityProfileFactory.default(activity);val air=weather?.apparentTemperatureCelsius?:weather?.airTemperatureCelsius;val available=mapOf(MarineParameter.APPARENT_TEMPERATURE to air,MarineParameter.AIR_TEMPERATURE to air,MarineParameter.SEA_TEMPERATURE to temp,MarineParameter.WAVE_HEIGHT to wave,MarineParameter.WAVE_PERIOD to period,MarineParameter.SWELL_HEIGHT to future?.swellWaveHeightM,MarineParameter.SWELL_PERIOD to future?.swellWavePeriodS,MarineParameter.WIND_SPEED to wind,MarineParameter.WIND_GUST to weather?.windGustMetersPerSecond,MarineParameter.PRECIPITATION to weather?.precipitationMillimeters,MarineParameter.THUNDERSTORM_PROBABILITY to weather?.thunderstormProbabilityPercent);if(profile.requiredParameters.count{available[it]!=null}>=profile.minimumRequiredParameterCount){val profileScore=activityProfileScore(profile,air,temp,wave,period,future?.swellWaveHeightM,future?.swellWavePeriodS,wind,weather?.windGustMetersPerSecond,weather?.precipitationMillimeters,weather?.thunderstormProbabilityPercent);score=minOf(score.coerceIn(0,100),profileScore)}else score=score.coerceIn(0,100);val level=when(score){in 90..100->ActivitySuitabilityLevel.EXCELLENT;in 70..89->ActivitySuitabilityLevel.GOOD;in 50..69->ActivitySuitabilityLevel.ACCEPTABLE;in 25..49->ActivitySuitabilityLevel.POOR;else->ActivitySuitabilityLevel.DANGEROUS};return result(activity,score,level,"Вълни %.1f m · %s".format(wave,wind?.let{"Вятър %.1f m/s".format(it)}?:"няма данни за вятър"),reasons,warnings,source(observation,future,cached))
 }
 private fun source(o:BuoyObservation?,f:MarineForecastPoint?,cached:Boolean)=when{cached->SuitabilitySourceType.CACHED;o!=null&&f!=null->SuitabilitySourceType.MIXED;o!=null->SuitabilitySourceType.MEASUREMENT;else->SuitabilitySourceType.FORECAST}
 private fun result(a:MarineActivityType,s:Int,l:ActivitySuitabilityLevel,summary:String,r:List<String>,w:List<String>,source:SuitabilitySourceType)=ActivitySuitability(a,"selected",Instant.now(),l,s,if(l==ActivitySuitabilityLevel.POOR)when(a){MarineActivityType.SURFING->"Малки вълни за сърф";MarineActivityType.KITESURFING->"Недостатъчен вятър за кайтсърф";MarineActivityType.SAILING->"Слаб вятър за ветроходство";else->"Неподходящи условия"}else l.title,summary,r,w,source)
}
